export enum TokenType {
  // Structural
  PIPE = '|',
  TREE_DOWN = '╰──➤',
  BRACKET_OPEN = '[',
  BRACKET_CLOSE = ']',
  PAREN_OPEN = '(',
  PAREN_CLOSE = ')',
  BRACE_OPEN = '{',
  BRACE_CLOSE = '}',
  ANGLE_OPEN = '<',
  ANGLE_CLOSE = '>',
  
  // Keywords/Commands
  CALL = 'call~',
  CALL_BANG = 'call~!!',
  BUILD = 'build~',
  BUILD_BANG = 'Build~!!',
  CHECK = 'check~',
  IMPORT = 'import~',
  IMPORT_BANG = 'import~!!',
  STORE = 'store~',
  STORE_CAP = 'Store~',
  MANIFEST = '.mf~',
  SHOW = 'show~',
  SHOW_CAP = 'Show~',
  PANEL = 'Panel~',
  PANEL_BANG = 'Panel~!!',
  SIMCORE = 'SimCore~!!',
  TAG = 'TAG~',
  SIGNATURE = 'Signiture~!!',
  ASK = 'ASK~',
  ASK_BANG = 'ASK~!!',
  ACCESS = 'ACCESS~',
  ACCESS_BANG = 'ACCESS~!!',
  SNIFF = 'Sniff~',
  SNIFF_LOWER = 'sniff~',
  SNIFF_BANG = 'sniff!~!!',
  DETECT = 'detect~',
  DETECT_BANG = 'detect~!!',
  FETCH = 'Fetch~!!',
  FETCH_LOWER = 'Fetch~',
  START = 'Start~',
  ARGU = 'Argu~!!',
  ARGUR = 'Argur~!!',
  PAIR = 'Pair~',
  DEVICE = 'Device~',
  DEVICE_BANG = 'Device~!!',
  NCOM = 'NCOM~',
  NCOM_BANG = 'NCOM~!!',
  CORE = 'core~',
  CORE_BANG = 'CORE~!!',
  UWB = 'UWB~',
  UWB_BANG = 'UWB~!!',
  SEND = 'SEND~',
  SEND_BANG = 'SEND~!!',
  GET = 'get~',
  GET_CAP = 'Get~',
  SENSE = 'Sense~!!',
  FEED = 'Feed~',
  SOURCE = 'Source~',
  CONTROLS = 'Controls~',
  PERMISSIONS = 'Permissions~',
  LOG = 'Log~',
  INJECT = 'Inject~',
  OVERRIDE = 'Override~',
  PERSIST = 'Persist~',
  SCOPE = 'Scope~',
  FORCE = 'Force~',
  FORCED = 'FORCED!!',
  SIM = 'Sim~',
  SPOOF = 'Spoof~',
  PANELS = 'Panels~',
  GRID = 'Grid~',
  ROWS = 'Rows~',
  COLUMNS = 'Columns~',
  TOTAL = 'Total~',
  RESIZE = 'Resize~',
  DRAG = 'Drag~',
  LOCK = 'Lock~',
  ID = 'ID~',
  TEXT = 'text~',
  TEXT_LOWER = 'text',
  COLOR = 'Color',
  SCAN = 'Scan',
  USER = 'USER',
  USER_LOWER = 'user',
  ACCOUNT = 'account~',
  ACCOUNT_BANG = 'account~!!',
  AUTH = 'Auth~',
  AUTH_BANG = 'Auth~!!',
  LINK = 'Link_$',
  APP = 'APP',
  OS = 'OS',
  DEV = 'DEV',
  DEV_ONLY = 'DEV_ONLY~!!',
  DEV_BANG = 'DEV~!!',
  SENSOR = 'sensor',
  SENSORS = 'sensors',
  SENSORS_BANG = 'sensors~!!',
  CHANNELS = 'channels~',
  TARGETS = 'targets',
  LIVE = 'LIVE',
  ALWAYS = 'ALWAYS',
  DYNAMIC = 'Dynamic',
  ALL = 'ALL',
  DATA = 'data',
  VALUE = 'value',
  STREAM = 'stream',
  TARGET = 'target',
  SESSION = 'session',
  FIRMWARE = 'firmware',
  
  // Special operators
  SHELL_BRIDGE = '~!!',
  SHELL_COMMENT = '///',
  SHELL_DOUBLE_COMMENT = '//',
  COLON = ':',
  EQUALS = '=',
  TILDE = '~',
  BANG = '!',
  DOLLAR = '$',
  AT = '@',
  DOT = '.',
  COMMA = ',',
  SLASH = '/',
  TRIPLE_PIPE = '|||',
  EXCLAIM_PIPE = '|!!|',
  
  // Literals
  IDENTIFIER = 'IDENTIFIER',
  STRING = 'STRING',
  NUMBER = 'NUMBER',
  PLX_EXT = 'PLX_EXT',
  
  // Meta
  EOF = 'EOF',
  NEWLINE = 'NEWLINE',
  INDENT = 'INDENT',
  WHITESPACE = 'WHITESPACE',
  UNKNOWN = 'UNKNOWN'
}

export interface Token {
  type: TokenType;
  value: string;
  position: Position;
}

export interface Position {
  line: number;
  column: number;
  index: number;
}

export function createToken(type: TokenType, value: string, position: Position): Token {
  return { type, value, position };
}
